language: python
dist: focal

python:
  - "3.8"

before_install:
  - sudo apt-get update
  - sudo apt-get install dbus-x11 libcairo2-dev libdbus-1-dev libgirepository1.0-dev pkg-config python-nose
  - python -m pip install --upgrade pip

install:
  - pip3 install dbus-python PyGObject

script:
  - make test
  - make testinstall
